### ISSUE TITLE
[BF2] The provided username includes unallowed characters

### ISSUE THREAD

**Issue by Shark-93** [leonlarsson/bfstats-api#1]
Dear, I hope I am in the right repo...
`/bf2 stats` Overview `platform` BF2Hub `username` [Ca0S.ad](https://www.bf2hub.com/stats/67156352)
throws the error message in the title.

Thank you

**Comment by leonlarsson** [comment]
Thanks for reporting! I have relaxed the username validation for BF2, and this username (and others) should now work.

**Comment by Shark-93** [comment]
Kill confirmed! Very fast, bravo Leon
